---
- name: Deploy Checkmk plugins for user password expiration and logins
  hosts: all
  become: yes

  vars:
    script_filename: "Checkmk_linux.txt"
    username: "testuser"

  tasks:

    - name: Set expiry date (3 days from now)
      command: date -d "+3 days" +%Y-%m-%d
      register: expiry_date
      changed_when: false

    - name: Create user that expires after 3 days
      user:
        name: "{{ username }}"
        shell: /bin/bash
        create_home: yes
        expires: "{{ expiry_date.stdout | to_datetime('%Y-%m-%d') | as_timestamp }}"
        state: present

    - name: Copy Checkmk script to server
      copy:
        src: "{{ script_filename }}"
        dest: "/tmp/{{ script_filename }}"
        mode: '0755'

    - name: Execute Checkmk script
      command: "/tmp/{{ script_filename }}"
      args:
        chdir: /tmp
