---
- name: Multi-OS Security Patching & Audit Reporting
  hosts: all
  become: yes
  vars:
    report_file: "/tmp/patch_audit_{{ lookup('pipe', 'date +%Y%m%d_%H%M') }}.csv"
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    smtp_user: "ignioservices@gmail.com"
    smtp_pass: "{{ vault_smtp_password }}" 
    email_recipient: "auditor@yourcompany.com"

  tasks:
    - name: 1. Initialize variables
      set_fact:
        patch_status: "No updates needed"
        reboot_required: "No"

    # --- RHEL SECTION ---
    - name: 2. Patch RedHat
      block:
        - name: RHEL | Upgrade
          dnf: { name: "*", state: latest, skip_if_unavailable: yes }
          register: rhel_out
        - name: RHEL | Check Reboot
          command: needs-restarting -r
          register: rhel_reboot_check
          ignore_errors: yes
          changed_when: false
        - name: RHEL | Record
          set_fact:
            patch_status: "{{ 'Success' if rhel_out.changed else 'No updates needed' }}"
            reboot_required: "{{ 'Yes' if rhel_reboot_check.rc | default(0) != 0 else 'No' }}"
      when: ansible_os_family == "RedHat"
      rescue:
        - set_fact: { patch_status: "Failed" }

    # --- DEBIAN SECTION ---
    - name: 3. Patch Debian
      block:
        - name: Debian | Upgrade
          apt: { upgrade: dist, update_cache: yes }
          register: deb_out
        - name: Debian | Check Reboot
          stat: { path: /var/run/reboot-required }
          register: reboot_file
        - name: Debian | Record
          set_fact:
            patch_status: "{{ 'Success' if deb_out.changed else 'No updates needed' }}"
            reboot_required: "{{ 'Yes' if reboot_file.stat.exists else 'No' }}"
      when: ansible_os_family == "Debian"
      rescue:
        - set_fact: { patch_status: "Failed" }

    # --- REPORT & EMAIL ---
    - name: 4. Build Report
      run_once: true
      delegate_to: localhost
      copy:
        dest: "{{ report_file }}"
        content: "Hostname,IP,OS,Status,Reboot_Required,Timestamp\n"

    - name: 5. Append data
      delegate_to: localhost
      lineinfile:
        path: "{{ report_file }}"
        line: "{{ inventory_hostname }},{{ ansible_default_ipv4.address }},{{ ansible_os_family }},{{ patch_status }},{{ reboot_required }},{{ ansible_date_time.iso8601 }}"

    - name: 6. Send Email
      run_once: true
      delegate_to: localhost
      community.general.mail: # Use FQCN here
        host: "{{ smtp_server }}"
        port: "{{ smtp_port }}"
        username: "{{ smtp_user }}"
        password: "{{ smtp_pass }}"
        secure: starttls
        to: "{{ email_recipient }}"
        subject: "PROD AUDIT: OS Patching Report"
        body: "Patching complete. CSV attached."
        attach: "{{ report_file }}"
