---
- name: Multi-OS Security Patching & Audit Reporting
  hosts: all
  become: yes
  vars:
    report_file: "/tmp/patch_audit_{{ lookup('pipe', 'date +%Y%m%d_%H%M') }}.csv"
    
    # Gmail SMTP Configuration
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    smtp_user: "ignioservices@gmail.com"
    smtp_pass: "{{ vault_smtp_password }}" 
    email_recipient: "michael.obateru@cwg-plc.com"

  tasks:
    - name: 1. Initialize variables for report
      set_fact:
        patch_status: "No updates needed"
        update_count: 0
        reboot_required: "No"

    # --- RHEL / CENTOS / ROCKY SECTION ---
    - name: 2. Patch RedHat-based systems
      block:
        - name: RHEL | Apply updates (Skip broken repos)
          dnf:
            name: "*"
            state: latest
            skip_if_unavailable: yes
          register: rhel_out
          when: ansible_os_family == "RedHat"

        - name: RHEL | Record status
          set_fact:
            patch_status: "{{ 'Success' if rhel_out.changed else 'No updates needed' }}"
            update_count: "{{ rhel_out.results | length if rhel_out.changed else 0 }}"
      rescue:
        - set_fact:
            patch_status: "Failed - Repo/Network Issue"
      when: ansible_os_family == "RedHat"

    # --- DEBIAN / UBUNTU SECTION ---
    - name: 3. Patch Debian-based systems
      block:
        - name: Debian | Update cache (Ignore broken 3rd party)
          apt:
            update_cache: yes
          ignore_errors: yes
          when: ansible_os_family == "Debian"

        - name: Debian | Upgrade all packages
          apt:
            upgrade: dist
          register: deb_out
          when: ansible_os_family == "Debian"

        - name: Debian | Check if reboot required
          stat:
            path: /var/run/reboot-required
          register: reboot_file

        - name: Debian | Record status
          set_fact:
            patch_status: "{{ 'Success' if deb_out.changed else 'No updates needed' }}"
            reboot_required: "{{ 'Yes' if reboot_file.stat.exists else 'No' }}"
      rescue:
        - set_fact:
            patch_status: "Failed - Dependency Issue"
      when: ansible_os_family == "Debian"

    # --- AUDIT REPORT GENERATION ---
    - name: 4. Create CSV Header on AWX Controller
      run_once: true
      delegate_to: localhost
      copy:
        dest: "{{ report_file }}"
        content: "Hostname,IP_Address,OS_Family,Status,Reboot_Required,Timestamp\n"

    - name: 5. Append host data to CSV
      delegate_to: localhost
      lineinfile:
        path: "{{ report_file }}"
        line: "{{ inventory_hostname }},{{ ansible_default_ipv4.address }},{{ ansible_os_family }},{{ patch_status }},{{ reboot_required }},{{ ansible_date_time.iso8601 }}"

    - name: 6. Send Audit Report via Gmail
      run_once: true
      delegate_to: localhost
      mail:
        host: "{{ smtp_server }}"
        port: "{{ smtp_port }}"
        username: "{{ smtp_user }}"
        password: "{{ smtp_pass }}"
        secure: starttls
        to: "{{ email_recipient }}"
        subject: "PROD AUDIT: OS Patching Report - {{ ansible_date_time.date }}"
        body: "Automated patch run complete for {{ ansible_play_hosts_all | length }} servers. See attached CSV."
        attach: "{{ report_file }}"
      ignore_errors: yes
