---
- name: Debug and Force Install Environment
  hosts: localhost
  gather_facts: no
  become: no
  tasks:
    - name: FORCE INSTALL | Nutanix SDK
      # We use 'python3 -m pip' to ensure it uses the exact same version as the runner
      command: python3 -m pip install ntnx-prism-py-client ntnx-vmm-py-client --user
      changed_when: true

    - name: VERIFY | Test Python Import with Path Fix
      shell: |
        # This line tells Python to look in the 'user' folder we just installed to
        export PYTHONPATH=$PYTHONPATH:$(python3 -m site --user-site)
        python3 -c "import ntnx_prism_py_client; import ntnx_vmm_py_client; print('IMPORT SUCCESSFUL')"
      register: import_test
      ignore_errors: yes

    - debug:
        msg: 
          - "Python Import: {{ import_test.stdout if import_test.rc == 0 else 'STILL FAILING' }}"
          - "User Site Path: {{ import_test.stderr if import_test.rc != 0 }}"
