- hosts: localhost
  tasks:
    - name: List all available Nutanix modules
      shell: "ansible-doc -l | grep nutanix.ncp"
      register: modules_list

    - debug:
        var: modules_list.stdout_lines
