---
- name: Test connectivity to 8.8.8.8
  hosts: all
  become_user: root
  gather_facts: no

  tasks:
    - name: Run ICMP ping to 8.8.8.8
      ansible.builtin.shell: ping -c 2 8.8.8.8
      register: ping_result
      ignore_errors: no

    - name: Show ping output
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }} -> {{ ping_result.stdout | default('Ping failed') }}"
