---
- name: Check connectivity to Google DNS
  hosts: all
  gather_facts: no

  tasks:
    - name: Try HTTPS request to Google DNS (8.8.8.8)
      ansible.builtin.uri:
        url: https://8.8.8.8
        method: GET
        return_content: no
        validate_certs: no
      register: result
      ignore_errors: no

    - name: Show result
      ansible.builtin.debug:
        var: result
      when: result is defined
 
