---
- name: Test connectivity to 8.8.8.8
  hosts: all
  become: true
  gather_facts: yes

  tasks:
    - name: Ping 8.8.8.8 using command
      ansible.builtin.command: ping -c 2 8.8.8.8
      register: ping_result
      ignore_errors: yes

    - name: Show ping result
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }} -> {{ ping_result.stdout | default('Ping failed') }}"
