---
- name: Ping all servers to 8.8.8.8
  hosts: all
  become: true
  gather_facts: no

  tasks:
    - name: Run ICMP ping to 8.8.8.8
      ansible.builtin.command: ping -c 4 8.8.8.8
      register: ping_result

    - name: Show ping output
      ansible.builtin.debug:
        var: ping_result.stdout
