---
- name: Test Internet Connectivity
  hosts: all
  gather_facts: no
  tasks:
    - name: Ping 8.8.8.8 to test internet connectivity
      ansible.builtin.shell: ping -c 4 8.8.8.8
      register: ping_result
      ignore_errors: yes

    - name: Show ping output
      ansible.builtin.debug:
        var: ping_result.stdout

    - name: Fail if ping was unsuccessful
      ansible.builtin.fail:
        msg: "Internet connectivity test failed. Cannot reach 8.8.8.8"
      when: ping_result.rc != 0
