---
- name: Patch and update Ubuntu servers
  hosts: all
  become: yes
  gather_facts: yes
 
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      tags: update_cache
 
    - name: Upgrade all packages to latest version
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      tags: upgrade
