---
- name: Windows Daily Health Check with CSV Email Report
  hosts: all
  gather_facts: yes
  
  vars:
    report_file: "/tmp/health_check_{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}.csv"
    email_recipient: "abdullateef.adekogbe@cwg-plc.com"
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    smtp_user: "ignioservices@gmail.com"
    # Services that might not exist on all server roles
    critical_services:
      - Dhcp
      - Dnscache
      - LanmanServer
      - WinRM
      - W3SVC          # Web servers only
      - MSSQLSERVER    # SQL servers only

  tasks:
    - name: 1. Initialize health metrics
      set_fact:
        disk_status: "OK"
        service_status: "OK"
        cpu_usage: "N/A"
        mem_usage: "N/A"
        reporting_ip: "{{ ansible_host | default(inventory_hostname) }}"
        full_os_name: "{{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: 2. Check disk space (all drives)
      win_shell: |
        $disks = Get-PSDrive -PSProvider FileSystem | Where-Object {$_.Used -gt 0} | 
                 Select-Object Name, @{n='FreePct';e={[math]::Round(($_.Free/($_.Used+$_.Free))*100,1)}}
        $critical = $disks | Where-Object {$_.FreePct -lt 10}
        if ($critical) {
          "CRITICAL: " + ($critical | ForEach-Object {"$($_.Name):$($_.FreePct)%"} | Join-String -Separator ", ")
        } else {
          "OK"
        }
      register: disk_check
      changed_when: false
      ignore_errors: yes

    - name: 3. Check critical services (gracefully handle missing services)
      win_service:
        name: "{{ item }}"
        state: started
      loop: "{{ critical_services }}"
      ignore_errors: yes  # Critical: prevents playbook failure on missing services
      register: service_check

    - name: 4. Evaluate service health (safe attribute access)
      set_fact:
        failed_services: >-
          {{
            service_check.results
            | selectattr('status', 'defined')
            | rejectattr('status', 'equalto', 'running')
            | map(attribute='name')
            | list
          }}
        missing_services: >-
          {{
            service_check.results
            | rejectattr('status', 'defined')
            | map(attribute='name')
            | list
          }}
      no_log: true  # Avoid leaking service names in logs

    - name: 5. Format service status string
      set_fact:
        service_status: >-
          {{
            (failed_services | length > 0) | ternary(
              'FAILED: ' + failed_services | join(', '),
              (missing_services | length > 0) | ternary(
                'MISSING: ' + missing_services | join(', '),
                'OK'
              )
            )
          }}

    - name: 6. Get CPU/Memory usage
      win_shell: |
        try {
          $cpu = (Get-Counter '\Processor(_Total)\% Processor Time' -SampleInterval 1 -MaxSamples 3 -ErrorAction Stop).CounterSamples.CookedValue | Measure-Object -Average | % Average
        } catch {
          $cpu = "N/A"
        }
        try {
          $mem = Get-CimInstance Win32_OperatingSystem -ErrorAction Stop
          $memUsed = 100 - ($mem.FreePhysicalMemory / $mem.TotalVisibleMemorySize * 100)
        } catch {
          $memUsed = "N/A"
        }
        "$cpu,$memUsed"
      register: perf_check
      changed_when: false
      ignore_errors: yes

    - name: 7. Parse performance metrics safely
      set_fact:
        cpu_usage: "{{ perf_check.stdout.split(',')[0] | default('N/A') | trim }}"
        mem_usage: "{{ perf_check.stdout.split(',')[1] | default('N/A') | trim }}"

    - name: 8. Create CSV header (run ONCE on controller before any hosts)
      run_once: true
      delegate_to: localhost
      become: no
      copy:
        dest: "{{ report_file }}"
        content: "Hostname,IP_Address,OS_Version,Disk_Status,CPU_Usage(%),Memory_Usage(%),Service_Status,Timestamp\n"
      when: 
        - ansible_play_batch | length > 0  # Only run if hosts exist

    - name: 9. Wait for header file to exist (prevent race condition)
      wait_for:
        path: "{{ report_file }}"
        timeout: 10
      delegate_to: localhost
      become: no

    - name: 10. Append host health data to CSV
      delegate_to: localhost
      become: no
      throttle: 1  # Serialize writes to avoid corruption
      lineinfile:
        path: "{{ report_file }}"
        line: "{{ inventory_hostname }},{{ reporting_ip }},{{ full_os_name }},{{ disk_check.stdout | default('ERROR') | replace(',', ';') | trim }},{{ cpu_usage }},{{ mem_usage }},{{ service_status | replace(',', ';') | trim }},{{ lookup('pipe','date --iso-8601=seconds') }}"
      ignore_errors: yes

    - name: 11. Wait for all hosts to finish writing (barrier sync)
      wait_for:
        timeout: 5
      run_once: true
      delegate_to: localhost
      become: no
      when: 
        - ansible_play_hosts.index(inventory_hostname) == (ansible_play_hosts | length - 1)

    - name: 12. Email final health report (ALWAYS sends, even on partial failures)
      run_once: true
      delegate_to: localhost
      become: no
      community.general.mail:
        host: "{{ smtp_server }}"
        port: "{{ smtp_port }}"
        username: "{{ smtp_user }}"
        password: "{{ vault_smtp_password }}"
        secure: starttls
        to: "{{ email_recipient }}"
        subject: "✅ WINDOWS HEALTH CHECK: {{ ansible_play_batch | length }} servers checked {{ lookup('pipe', 'date +%Y-%m-%d') }}"
        body: |
          Daily health check completed at {{ lookup('pipe', 'date') }}.

          Summary:
          • Total servers: {{ ansible_play_hosts | length }}
          • Successfully checked: {{ ansible_play_batch | length }}
          • Report attached: {{ report_file | basename }}

          ⚠️ Note: Some services may be MISSING (not installed) on certain server roles.
        attach: "{{ report_file }}"
      when: 
        - report_file is exists
      ignore_errors: yes  # Never fail the entire playbook due to email issues
