---
- name: Windows Daily Health Check
  hosts: all
  gather_facts: yes

  vars:
    # SMTP settings
    email_recipient: "abdullateef.adekogbe@cwg-plc.com"
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    smtp_user: "ignioservices@gmail.com"

  tasks:
    - name: Run health check on Windows host
      win_shell: |
        $disk = "OK"
        $disks = Get-PSDrive -PSProvider FileSystem | Where {$_.Used -gt 0}
        $low = $disks | Where {($_.Free/($_.Used+$_.Free)*100) -lt 10}
        if ($low) { $disk = "CRITICAL: " + (($low | % {"$($_.Name):$([math]::Round($_.Free/($_.Used+$_.Free)*100,1))%"}) -join ", ") }
        
        $svc = "OK"
        $failed = @()
        foreach ($s in @('Dnscache','LanmanServer','WinRM')) {
          $x = Get-Service $s -EA 0
          if ($x -and $x.Status -ne 'Running') { $failed += $s }
        }
        if ($failed) { $svc = "FAILED: " + ($failed -join ', ') }
        
        $cpu = (Get-Counter '\Processor(_Total)\% Processor Time' -SampleInterval 1 -MaxSamples 3).CounterSamples.CookedValue | Measure -Average | % Average
        $mem = (Get-CimInstance Win32_OperatingSystem)
        $used = 100 - ($mem.FreePhysicalMemory / $mem.TotalVisibleMemorySize * 100)
        
        "$disk|$svc|$([math]::Round($cpu,1))|$([math]::Round($used,1))"
      register: hc
      ignore_errors: yes
      changed_when: false

    - name: Parse results safely
      set_fact:
        disk_status: "{{ hc.stdout.split('|')[0] | default('ERROR') | trim }}"
        svc_status: "{{ hc.stdout.split('|')[1] | default('ERROR') | trim }}"
        cpu_usage: "{{ hc.stdout.split('|')[2] | default('N/A') | trim }}"
        mem_usage: "{{ hc.stdout.split('|')[3] | default('N/A') | trim }}"

    - name: Generate timestamp ONCE on localhost (critical fix)
      delegate_to: localhost
      run_once: true
      set_fact:
        report_timestamp: "{{ '%Y%m%d_%H%M%S' | strftime }}"
      when: hostvars[inventory_hostname].report_timestamp is not defined

    - name: Build and email report from localhost (multi-host aware)
      delegate_to: localhost
      # REMOVED run_once: true → now runs for EVERY host to collect all data
      vars:
        report_file: "/tmp/health_{{ hostvars[inventory_hostname].report_timestamp }}.csv"
      block:
        - name: Create CSV header (only FIRST host creates header)
          copy:
            content: "Inventory_Hostname,IP_Address,OS_Version,Disk_Status,Services_Status,CPU_Usage(%),Memory_Usage(%),Timestamp\n"
            dest: "{{ report_file }}"
            mode: '0644'
          when: inventory_hostname == ansible_play_hosts[0]

        - name: Append THIS host's data to CSV (ALL hosts run this)
          lineinfile:
            path: "{{ report_file }}"
            line: "{{ inventory_hostname }},{{ ansible_host }},{{ ansible_distribution }} {{ ansible_distribution_version }},{{ disk_status | replace(',', ';') }},{{ svc_status | replace(',', ';') }},{{ cpu_usage }},{{ mem_usage }},{{ '%Y-%m-%d %H:%M:%S' | strftime }}"
          throttle: 1  # Critical: prevents file write collisions with many hosts

        - name: Send email with FULL report (only LAST host sends email)
          community.general.mail:
            host: "{{ smtp_server }}"
            port: "{{ smtp_port }}"
            username: "{{ smtp_user }}"
            password: "{{ vault_smtp_password }}"
            secure: starttls
            to: "{{ email_recipient }}"
            subject: "✅ Health Report - {{ ansible_play_hosts | length }} servers ({{ '%Y-%m-%d' | strftime }})"
            body: |
              Health check completed for {{ ansible_play_hosts | length }} server(s).
              
              Servers checked:
              {% for host in ansible_play_hosts %}
              • {{ host }}
              {% endfor %}
              
              Full report attached.
            attach: "{{ report_file }}"
          when: inventory_hostname == ansible_play_hosts[-1]
          ignore_errors: yes
