---
- name: Windows Daily Health Check
  hosts: all
  gather_facts: yes

  vars:
    report_file: "/tmp/health_{{ '%Y%m%d_%H%M%S' | strftime }}.csv"
    email_recipient: "abdullateef.adekogbe@cwg-plc.com"
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    smtp_user: "ignioservices@gmail.com"

  tasks:
    - name: Run health check on Windows host
      win_shell: |
        # Disk check
        $disk = "OK"
        $disks = Get-PSDrive -PSProvider FileSystem | Where {$_.Used -gt 0}
        $low = $disks | Where {($_.Free/($_.Used+$_.Free)*100) -lt 10}
        if ($low) { $disk = "CRITICAL: " + (($low | % {"$($_.Name):$([math]::Round($_.Free/($_.Used+$_.Free)*100,1))%"}) -join ", ") }
        
        # Service check (universal services only)
        $svc = "OK"
        $failed = @()
        foreach ($s in @('Dnscache','LanmanServer','WinRM')) {
          $x = Get-Service $s -EA 0
          if ($x -and $x.Status -ne 'Running') { $failed += $s }
        }
        if ($failed) { $svc = "FAILED: " + ($failed -join ', ') }
        
        # CPU/Memory
        $cpu = (Get-Counter '\Processor(_Total)\% Processor Time' -SampleInterval 1 -MaxSamples 3).CounterSamples.CookedValue | Measure -Average | % Average
        $mem = (Get-CimInstance Win32_OperatingSystem)
        $used = 100 - ($mem.FreePhysicalMemory / $mem.TotalVisibleMemorySize * 100)
        
        # Output pipe-delimited for simple parsing
        "$disk|$svc|$([math]::Round($cpu,1))|$([math]::Round($used,1))"
      register: hc
      ignore_errors: yes
      changed_when: false

    - name: Parse health results
      set_fact:
        disk_status: "{{ hc.stdout.split('|')[0] | default('ERROR') | trim }}"
        svc_status: "{{ hc.stdout.split('|')[1] | default('ERROR') | trim }}"
        cpu_usage: "{{ hc.stdout.split('|')[2] | default('N/A') | trim }}"
        mem_usage: "{{ hc.stdout.split('|')[3] | default('N/A') | trim }}"

    - name: Create CSV report on controller (ALL IN ONE TASK - avoids race conditions)
      delegate_to: localhost
      run_once: true
      block:
        - name: Build CSV content in memory
          set_fact:
            csv_lines:
              - "Hostname,IP_Address,OS_Version,Disk_Status,Services_Status,CPU_Usage(%),Memory_Usage(%),Timestamp"
              - "{{ ansible_hostname }},{{ ansible_host | default(inventory_hostname) }},{{ ansible_distribution }},{{ disk_status | replace(',', ';') }},{{ svc_status | replace(',', ';') }},{{ cpu_usage }},{{ mem_usage }},{{ '%Y-%m-%d %H:%M:%S' | strftime }}"

        - name: Write complete CSV file atomically
          copy:
            content: "{{ csv_lines | join('\n') }}\n"
            dest: "{{ report_file }}"
            mode: '0644'

    - name: Email report (run once after all hosts)
      community.general.mail:
        host: "{{ smtp_server }}"
        port: "{{ smtp_port }}"
        username: "{{ smtp_user }}"
        password: "{{ vault_smtp_password }}"
        secure: starttls
        to: "{{ email_recipient }}"
        subject: "✅ Windows Health Report - {{ ansible_date_time.date }}"
        body: |
          Daily health check completed successfully.

          Servers checked: {{ ansible_play_batch | length }}
          Report generated: {{ '%Y-%m-%d %H:%M:%S' | strftime }}
        attach: "{{ report_file }}"
      delegate_to: localhost
      run_once: true
      when: report_file is exists
      ignore_errors: yes
