---
- name: Windows Daily Health Check
  hosts: all
  gather_facts: yes

  vars:
    # SMTP settings
    email_recipient: "abdullateef.adekogbe@cwg-plc.com"
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    smtp_user: "ignioservices@gmail.com"

  tasks:
    - name: Run health check on Windows host
      win_shell: |
        # Uptime in days
        $os = Get-CimInstance Win32_OperatingSystem -ErrorAction SilentlyContinue
        $uptime = (Get-Date) - $os.LastBootUpTime
        $uptime_days = [math]::Floor($uptime.TotalDays)
        
        # CPU usage %
        $cpu = (Get-Counter '\Processor(_Total)\% Processor Time' -SampleInterval 1 -MaxSamples 3 -ErrorAction SilentlyContinue).CounterSamples.CookedValue | Measure-Object -Average | % Average
        $cpu_pct = [math]::Round($cpu, 1)
        
        # Memory free in GB
        $mem_free_gb = [math]::Round($os.FreePhysicalMemory / 1024 / 1024, 2)
        
        # Disk C: and D: free space %
        $disk_c = Get-PSDrive C -ErrorAction SilentlyContinue
        $disk_c_free = if ($disk_c) { [math]::Round($disk_c.Free / ($disk_c.Free + $disk_c.Used) * 100, 1) } else { "N/A" }
        $disk_d = Get-PSDrive D -ErrorAction SilentlyContinue
        $disk_d_free = if ($disk_d) { [math]::Round($disk_d.Free / ($disk_d.Free + $disk_d.Used) * 100, 1) } else { "N/A" }
        
        # Last patch date
        $last_patch = Get-HotFix | Sort-Object InstalledOn -Descending | Select-Object -First 1 -ErrorAction SilentlyContinue
        $last_patch_date = if ($last_patch) { $last_patch.InstalledOn.ToString('yyyy-MM-dd') } else { "Never" }
        
        # Output 6 metrics pipe-delimited (removed StoppedServices, SystemErrors24h, AppErrors24h, BackupStatus)
        "$uptime_days|$cpu_pct|$mem_free_gb|$disk_c_free|$disk_d_free|$last_patch_date"
      register: hc
      ignore_errors: yes
      changed_when: false

    - name: Parse results safely
      set_fact:
        uptime_days: "{{ hc.stdout.split('|')[0] | default('N/A') | trim }}"
        cpu_pct: "{{ hc.stdout.split('|')[1] | default('N/A') | trim }}"
        mem_free_gb: "{{ hc.stdout.split('|')[2] | default('N/A') | trim }}"
        disk_c_free: "{{ hc.stdout.split('|')[3] | default('N/A') | trim }}"
        disk_d_free: "{{ hc.stdout.split('|')[4] | default('N/A') | trim }}"
        last_patch_date: "{{ hc.stdout.split('|')[5] | default('Never') | trim }}"

    - name: Generate timestamp ONCE on localhost (critical fix)
      delegate_to: localhost
      run_once: true
      set_fact:
        report_timestamp: "{{ '%Y%m%d_%H%M%S' | strftime }}"
      when: hostvars[inventory_hostname].report_timestamp is not defined

    - name: Build and email report from localhost (multi-host aware)
      delegate_to: localhost
      vars:
        report_file: "/tmp/health_{{ hostvars[inventory_hostname].report_timestamp }}.csv"
      block:
        - name: Create CSV header (only FIRST host creates header)
          copy:
            content: "Hostname,IP,UptimeDays,CPU%,MemFreeGB,DiskC_Free%,DiskD_Free%,LastPatchDate\n"
            dest: "{{ report_file }}"
            mode: '0644'
          when: inventory_hostname == ansible_play_hosts[0]

        - name: Append THIS host's data to CSV (ALL hosts run this)
          lineinfile:
            path: "{{ report_file }}"
            line: "{{ inventory_hostname }},{{ ansible_host }},{{ uptime_days }},{{ cpu_pct }},{{ mem_free_gb }},{{ disk_c_free }},{{ disk_d_free }},{{ last_patch_date }}"
          throttle: 1

        - name: Send email with FULL report (only LAST host sends email)
          community.general.mail:
            host: "{{ smtp_server }}"
            port: "{{ smtp_port }}"
            username: "{{ smtp_user }}"
            password: "{{ vault_smtp_password }}"
            secure: starttls
            to: "{{ email_recipient }}"
            subject: "✅ Health Report - {{ ansible_play_hosts | length }} servers ({{ '%Y-%m-%d' | strftime }})"
            body: |
              Health check completed for {{ ansible_play_hosts | length }} server(s).
              
              Servers checked:
              {% for host in ansible_play_hosts %}
              • {{ host }}
              {% endfor %}
              
              Full report attached.
            attach: "{{ report_file }}"
          when: inventory_hostname == ansible_play_hosts[-1]
          ignore_errors: yes
