---
- name: Windows Daily Health Check
  hosts: all
  gather_facts: yes

  vars:
    report_file: "/tmp/health_{{ '%Y%m%d_%H%M%S' | strftime }}.csv"
    email_recipient: "abdullateef.adekogbe@cwg-plc.com"
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    smtp_user: "ignioservices@gmail.com"

  tasks:
    - name: Run health check (disk, services, CPU, memory)
      win_shell: |
        $output = @{}
        
        # Disk check
        $disks = Get-PSDrive -PSProvider FileSystem | Where-Object {$_.Used -gt 0}
        $lowDisk = $disks | Where-Object {($_.Free/($_.Used+$_.Free)*100) -lt 10}
        if ($lowDisk) {
          $output.disk = "CRITICAL: " + ($lowDisk | ForEach-Object {"$($_.Name):$([math]::Round($_.Free/($_.Used+$_.Free)*100,1))%"} -join ", ")
        } else {
          $output.disk = "OK"
        }
        
        # Service check (only universal services)
        $failedServices = @()
        foreach ($svc in @('Dnscache','LanmanServer','WinRM')) {
          $s = Get-Service -Name $svc -ErrorAction SilentlyContinue
          if ($s -and $s.Status -ne 'Running') { $failedServices += $svc }
        }
        $output.services = if ($failedServices) { "FAILED: " + ($failedServices -join ', ') } else { "OK" }
        
        # CPU/Memory
        $cpu = (Get-Counter '\Processor(_Total)\% Processor Time' -SampleInterval 1 -MaxSamples 3).CounterSamples.CookedValue | Measure-Object -Average | % Average
        $mem = Get-CimInstance Win32_OperatingSystem
        $memUsed = 100 - ($mem.FreePhysicalMemory / $mem.TotalVisibleMemorySize * 100)
        
        $output.cpu = [math]::Round($cpu, 1)
        $output.mem = [math]::Round($memUsed, 1)
        $output.hostname = $env:COMPUTERNAME
        $output.ip = (Get-NetIPAddress -AddressFamily IPv4 -InterfaceAlias '*' | Select-Object -First 1).IPAddress
        
        $output | ConvertTo-Json
      register: health
      ignore_errors: yes
      changed_when: false

    - name: Set safe defaults if health check failed
      set_fact:
        disk_status: "{{ (health.stdout | from_json | default({})).disk | default('CHECK FAILED') }}"
        svc_status: "{{ (health.stdout | from_json | default({})).services | default('CHECK FAILED') }}"
        cpu_usage: "{{ (health.stdout | from_json | default({})).cpu | default('N/A') }}"
        mem_usage: "{{ (health.stdout | from_json | default({})).mem | default('N/A') }}"
        host_ip: "{{ (health.stdout | from_json | default({})).ip | default(ansible_host | default(inventory_hostname)) }}"

    - name: Create CSV header (once)
      copy:
        content: "Hostname,IP_Address,OS,Disk_Status,CPU_Usage,Memory_Usage,Services_Status,Time\n"
        dest: "{{ report_file }}"
      delegate_to: localhost
      run_once: true
      when: ansible_play_hosts.index(inventory_hostname) == 0

    - name: Append host data to CSV
      lineinfile:
        path: "{{ report_file }}"
        line: "{{ ansible_hostname }},{{ host_ip }},{{ ansible_distribution }},{{ disk_status | replace(',', ';') }},{{ cpu_usage }},{{ mem_usage }},{{ svc_status | replace(',', ';') }},{{ '%Y-%m-%d %H:%M:%S' | strftime }}"
      delegate_to: localhost
      throttle: 1

    - name: Send email report (once after all hosts)
      community.general.mail:
        host: "{{ smtp_server }}"
        port: "{{ smtp_port }}"
        username: "{{ smtp_user }}"
        password: "{{ vault_smtp_password }}"
        secure: starttls
        to: "{{ email_recipient }}"
        subject: "Windows Health Report - {{ ansible_date_time.date }}"
        body: "Daily health check completed for {{ ansible_play_batch | length }} server(s). See attached CSV."
        attach: "{{ report_file }}"
      delegate_to: localhost
      run_once: true
      when: 
        - ansible_play_hosts.index(inventory_hostname) == (ansible_play_hosts | length - 1)
        - report_file is exists
      ignore_errors: yes
