---
- name: Windows Daily Health Check with CSV Email Report
  hosts: all
  gather_facts: yes
  
  vars:
    report_file: "/tmp/health_check_{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}.csv"
    email_recipient: "abdullateef.adekogbe@cwg-plc.com"
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    smtp_user: "ignioservices@gmail.com"

  tasks:
    - name: 1. Initialize health metrics
      set_fact:
        disk_status: "OK"
        service_status: "OK"
        cpu_usage: "N/A"
        mem_usage: "N/A"
        reporting_ip: "{{ ansible_host | default(inventory_hostname) }}"
        full_os_name: "{{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: 2. Check disk space (all drives)
      win_shell: |
        $disks = Get-PSDrive -PSProvider FileSystem | Where-Object {$_.Used -gt 0} | 
                 Select-Object Name, @{n='FreePct';e={[math]::Round(($_.Free/($_.Used+$_.Free))*100,1)}}
        $critical = $disks | Where-Object {$_.FreePct -lt 10}
        if ($critical) {
          "CRITICAL: " + ($critical | ForEach-Object {"$($_.Name):$($_.FreePct)%"} | Join-String -Separator ", ")
        } else {
          "OK"
        }
      register: disk_check
      changed_when: false

    - name: 3. Check critical services
      win_service:
        name: "{{ item }}"
        state: started
      loop:
        - Dhcp
        - Dnscache
        - LanmanServer
        - WinRM
      ignore_errors: yes
      register: service_check

    - name: 4. Evaluate service health
      set_fact:
        service_status: >-
          {{
            service_check.results | rejectattr('status', 'equalto', 'running') | list | length > 0 |
            ternary(
              'FAILED: ' + (service_check.results | rejectattr('status', 'equalto', 'running') | map(attribute='name') | join(', ')),
              'OK'
            )
          }}

    - name: 5. Get CPU/Memory usage
      win_shell: |
        $cpu = (Get-Counter '\Processor(_Total)\% Processor Time' -SampleInterval 1 -MaxSamples 3).CounterSamples.CookedValue | Measure-Object -Average | % Average
        $mem = Get-CimInstance Win32_OperatingSystem
        $memUsed = 100 - ($mem.FreePhysicalMemory / $mem.TotalVisibleMemorySize * 100)
        "$([math]::Round($cpu,1)),$([math]::Round($memUsed,1))"
      register: perf_check
      changed_when: false

    - name: 6. Parse performance metrics
      set_fact:
        cpu_usage: "{{ perf_check.stdout.split(',')[0] | default('N/A') }}"
        mem_usage: "{{ perf_check.stdout.split(',')[1] | default('N/A') }}"

    - name: 7. Create CSV header (run once on controller)
      run_once: true
      delegate_to: localhost
      become: no
      copy:
        dest: "{{ report_file }}"
        content: "Hostname,IP_Address,OS_Version,Disk_Status,CPU_Usage(%),Memory_Usage(%),Service_Status,Timestamp\n"
      when: ansible_play_hosts.index(inventory_hostname) == 0  # Only first host creates header

    - name: 8. Append host health data to CSV
      delegate_to: localhost
      become: no
      throttle: 1  # Prevent race conditions when multiple hosts write simultaneously
      lineinfile:
        path: "{{ report_file }}"
        line: "{{ inventory_hostname }},{{ reporting_ip }},{{ full_os_name }},{{ disk_check.stdout | replace(',', ' ') }},{{ cpu_usage }},{{ mem_usage }},{{ service_status | replace(',', ' ') }},{{ lookup('pipe','date --iso-8601=seconds') }}"
      ignore_errors: yes

    - name: 9. Email final health report
      run_once: true
      delegate_to: localhost
      become: no
      community.general.mail:
        host: "{{ smtp_server }}"
        port: "{{ smtp_port }}"
        username: "{{ smtp_user }}"
        password: "{{ vault_smtp_password }}"
        secure: starttls
        to: "{{ email_recipient }}"
        subject: "WINDOWS HEALTH CHECK: Daily Report {{ lookup('pipe', 'date +%Y-%m-%d') }}"
        body: |
          Daily health check completed for {{ groups['all'] | length }} Windows servers.

          Summary:
          • Hosts checked: {{ ansible_play_batch | length }}
          • Report generated: {{ lookup('pipe', 'date') }}

          See attached CSV for detailed metrics (disk, CPU, memory, services).
        attach: "{{ report_file }}"
      when: 
        - report_file is exists
        - ansible_play_hosts.index(inventory_hostname) == (ansible_play_hosts | length - 1)  # Only last host sends email
