---
- name: Zabbix Agent Onboarding
  hosts: all
  become: yes
  vars:
    zabbix_server_ip: "192.168.184.84" 
    zabbix_version: "7.2.7"

  tasks:

    - name: Ensure required tools are present
      package:
        name: wget
        state: present

    - name: Install Zabbix Agent on RHEL/CentOS
      when: ansible_os_family == "RedHat"
      shell: |
        rpm -Uvh https://repo.zabbix.com/zabbix/{{ zabbix_version }}/rhel/$(rpm -E %{rhel})/x86_64/zabbix-release-{{ zabbix_version }}-3.el$(rpm -E %{rhel}).noarch.rpm
        dnf clean all -y
        dnf install zabbix-agent -y
      args:
        creates: /etc/zabbix/zabbix_agentd.conf

    - name: Install Zabbix Agent on Ubuntu/Debian
      when: ansible_os_family == "Debian"
      shell: |
        wget -q https://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu/pool/main/z/zabbix-release/zabbix-release_{{ zabbix_version }}-3+ubuntu$(lsb_release -rs)_all.deb
        dpkg -i zabbix-release_{{ zabbix_version }}-3+ubuntu$(lsb_release -rs)_all.deb
        apt update -y
        apt install zabbix-agent -y
      args:
        creates: /etc/zabbix/zabbix_agentd.conf

    - name: Configure Zabbix Agent
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^Server=', line: "Server={{ zabbix_server_ip }}" }
        - { regexp: '^ServerActive=', line: "ServerActive={{ zabbix_server_ip }}" }
        - { regexp: '^Hostname=', line: "Hostname={{ inventory_hostname }}" }

    - name: Enable and start Zabbix Agent service
      service:
        name: zabbix-agent
        state: started
        enabled: yes

    - name: Open Zabbix agent port
      ansible.posix.firewalld:
        port: 10050/tcp
        permanent: yes
        state: enabled
        immediate: yes

    - name: Open Zabbix agent port (optional)
      ansible.posix.firewalld:
        port: 10051/tcp
        permanent: yes
        state: enabled
        immediate: yes
